server:
  port: 8081
  servlet:
    context-path: /
spring:
  application:
    name: wool
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  freemarker:
    template-loader-path: classpath:/templates/
    suffix: .html
    request-context-attribute: request